name: workflow1
env: 
    VAR1: 10  
on :
[push]
jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: Step 1
        run: echo $VAR1


  job2:
    needs: job1
    runs-on : ubuntu-latest
    if: failure()
    steps:
      - name: Step 2
        run: echo "Execution job 2"
      