name: workflow2  
env:
    A: 3
    B: 2
on: 
  workflow_dispatch
jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: Step 1
        run: echo $A $B
  job2:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train Model
      run: |
        python mult.py
       
      